nickjj/flask-static-digest/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,57 +1,75 @@
-name: Deploy
+name: "CI"
 
 on:
+  pull_request:
+    branches:
+      - "*"
   push:
     branches:
-      - main
-  release:
-    types:
-      - published
+      - "main"
+      - "main"
 
 jobs:
-  build:
-    if: github.repository == 'hugovk/pypistats'
-    runs-on: ubuntu-latest
+  test:
+    runs-on: "ubuntu-latest"
 
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
+      - uses: "actions/checkout@v2"
 
-      - name: Cache
-        uses: actions/cache@v4
+      - name: "Set up Python 3.8"
+        uses: "actions/setup-python@v1"
         with:
-          path: ~/.cache/pip
-          key: deploy-${{ hashFiles('**/setup.py') }}
-          restore-keys: |
-            deploy-
+          python-version: "3.9"
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-
-      - name: Install dependencies
+      - name: "Install dependencies"
         run: |
-          python -m pip install -U pip
-          python -m pip install -U setuptools twine wheel
+          pip3 install flake8 Flask==1.1.2
+          pip3 install -e .
 
-      - name: Build package
+      - name: "Lint code base"
         run: |
-          python setup.py --version
-          python setup.py sdist --format=gztar bdist_wheel
-          twine check dist/*
+          flake8 .
 
-      - name: Publish package to PyPI
-        if: github.event.action == 'published'
-        uses: pypa/gh-action-pypi-publish@main
-        with:
-          user: __token__
-          password: ${{ secrets.pypi_password }}
+      - name: "Run test suite"
+        run: |
+          cd tests/example_app
+          export FLASK_APP=example.app
 
-      - name: Publish package to TestPyPI
-        uses: pypa/gh-action-pypi-publish@main
-        with:
-          user: __token__
-          password: ${{ secrets.test_pypi_password }}
-          repository_url: https://test.pypi.org/legacy/
+          ls -laR example/static/ | wc -l \
+          | grep -q "26" \
+          && (echo "File count before compiling test: pass" && exit 0) \
+          || (echo "File count before compiling test: fail" && exit 1)
+
+          flask digest compile \
+          && ls -laR example/static/ | wc -l \
+          | grep -q "36" \
+          && (echo "File count after compiling test: pass" && exit 0) \
+          || (echo "File count after compiling test: fail" && exit 1)
+
+          grep -q "js/modules/hello.js" example/static/cache_manifest.json \
+          && (echo "Cache manifest has nested file test: pass" && exit 0) \
+          || (echo "Cache manifest has nested file test: fail" && exit 1)
+
+          grep -q "js/modules/hello-d41d8cd98f00b204e9800998ecf8427e.js" example/static/cache_manifest.json \
+          && (echo "Cache manifest has digested file test: pass" && exit 0) \
+          || (echo "Cache manifest has digested file test: fail" && exit 1)
+
+          flask run &
+          sleep 5 \
+          && curl http://localhost:5000 \
+          | grep -q 'https://cdn.example.com/static/css/app-d41d8cd98f00b204e9800998ecf8427e.css' \
+          && (echo 'Stylesheet is md5 tagged test: pass' && exit 0) \
+          || (echo 'Stylesheet is md5 tagged test: fail' && exit 1)
+
+          flask digest clean \
+          && ls -laR example/static/ | wc -l \
+          | grep -q "26" \
+          && (echo "File count after cleaning test: pass" && exit 0) \
+          || (echo "File count after cleaning test: fail" && exit 1)
+
+          flask run -p 5001 &
+          sleep 5 \
+          && curl http://localhost:5001 \
+          | grep -q 'https://cdn.example.com/static/js/app.js' \
+          && (echo 'Javascript is not md5 tagged test: pass' && exit 0) \
+          || (echo 'Javascript is not md5 tagged test: fail' && exit 1)
