komuw/naz/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,32 +1,119 @@
-name: Tests
+# DOCS: https://help.github.com/en/articles/workflow-syntax-for-github-actions
 
-on: [push, pull_request]
+name: naz ci
+on: [pull_request, push]
 
 jobs:
-  test:
-    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
-    runs-on: ${{ matrix.os }}
 
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-        python-version: ["3.9", "3.10"]
-
+  static_analysis:
+    name: static_analysis
+    runs-on: ubuntu-latest
+    timeout-minutes: 4
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
+      - name: Set up python
+        uses: actions/setup-python@v1
         with:
-          python-version: ${{ matrix.python-version }}
+          python-version: '3.9'
 
-      - name: Install dependencies
+      - name: Check out code
+        uses: actions/checkout@v1
+  
+      # TODO: fix this, for main branch it fails
+      - name: check if changes have release notes
+        if: github.ref != 'refs/heads/main'
+        env:
+          GIT_BRANCH: ${{ github.ref }}
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          if [ "$GIT_BRANCH" == "main" ]; then
+              printf "\n $GIT_BRANCH branch, ignoring check for relese notes \n"
+          else
+              ChangedFiles=`git diff --name-only origin/main`
+              echo $ChangedFiles
+              case "$ChangedFiles" in
+                *CHANGELOG.*)
+                    printf "\n Thanks, your commits include update to release notes. \n";;
+                *)
+                    printf "\n You should add release notes to CHANGELOG.md \n" && exit 77;;
+              esac
+          fi
 
-      - name: Run pytest
-        run: python -m pytest --cov-report=xml --cov=symspellpy
+      - name: install apt and pip deps
+        run: |
+          pwd; ls -lsha
+          sudo apt -y update; sudo apt-get -y install pandoc
+          pip install -e .[dev,test,benchmarks]
+          find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
 
-      - name: Upload code coverage
-        uses: codecov/codecov-action@v2
+      - name: run them analyzers
+        run: |
+          black --line-length=100 --check . ||  { printf "\\n\\t please use black to format your code."; exit 77; }
+          flake8 .
+          pylint --enable=E --disable=W,R,C naz/ tests/ cli/ documentation/ examples/ benchmarks/
+          bandit -r --exclude .venv -ll .
+          # to find types, use reveal_type eg: reveal_type(asyncio.get_event_loop())
+          # see: http://mypy.readthedocs.io/en/latest/common_issues.html#displaying-the-type-of-an-expression
+          mypy --show-column-numbers --ignore-missing-imports -p cli -p naz #--strict
+          pytype --verbosity 0 --python-version 3.6 --protocols --strict-import --keep-going naz/ cli/
+        env:
+          PYTHONASYNCIODEBUG: '1'
+
+  tests:
+    name: tests
+    runs-on: ubuntu-latest
+    timeout-minutes: 4
+    steps:
+      - name: Set up python
+        uses: actions/setup-python@v1
+        with:
+          python-version: '3.9'
+
+      - name: Check out code
+        uses: actions/checkout@v1
+  
+      - name: install apt and pip deps
+        run: |
+          pwd; ls -lsha
+          sudo apt -y update; sudo apt-get -y install curl pandoc
+          pip install -e .[dev,test,benchmarks]
+          find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
+
+      - name: run tests
+        run: |
+          naz-cli --version
+          naz-cli --help
+          naz-cli --client examples.example_config.client --dry-run
+          coverage erase
+          export CI_ENVIRONMENT=Yes && coverage run --omit="*tests*,*examples/*,*.virtualenvs/*,*virtualenv/*,*.venv/*,*__init__*" -m unittest discover -v -s . && bash <(curl -s https://codecov.io/bash)
+          coverage report --show-missing --fail-under=84
+        env:
+          PYTHONASYNCIODEBUG: '1'
+
+  docs:
+    name: docs
+    runs-on: ubuntu-latest
+    timeout-minutes: 3
+    steps:
+      - name: Set up python
+        uses: actions/setup-python@v1
+        with:
+          python-version: '3.9'
+
+      - name: Check out code
+        uses: actions/checkout@v1
+  
+      - name: install apt and pip deps
+        run: |
+          pwd; ls -lsha
+          sudo apt -y update; sudo apt-get -y install pandoc
+          pip install -e .[dev,test,benchmarks]
+          find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
+
+      - name: check docs are okay
+        run: |
+          sphinx-build -a -E documentation/sphinx-docs/ docs/
+          stat docs/.nojekyll # make sure that file exists.
+
+
+  # deploy:
+  #   name: deploy
+  #   runs-on: ubuntu-latest
