pykeen/pykeen/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,101 +1,78 @@
-name: Continuous integration
+name: Tests
 
-on:
-  push: # run when commits are added to main or develop
-    branches:
-      - main
-      - develop
-  pull_request: # run on pr's against main or develop
-    branches:
-      - main
-      - develop
-
-env:
-  default-python: "3.9"
+on: [ push ]
 
 jobs:
-
-  check-coding-style:
-    name: Check coding style
+  lint:
+    if: "!contains(github.event.head_commit.message, 'skip ci')"
+    name: Lint
     runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Set up Python ${{ env.default-python }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ env.default-python }}
-      - name: Upgrade pip, Install nox
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install nox
-      - name: Check coding style
-        run: |
-          nox --error-on-missing-interpreters --non-interactive --session lint
-
-  check-static-types:
-    name: Check static types
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Set up Python ${{ env.default-python }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ env.default-python }}
-      - name: Upgrade pip, Install nox
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install nox
-      - name: Check static types
-        run: |
-          nox --error-on-missing-interpreters --non-interactive --session types
-
-  tests:
-    name: Run tests
-    runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ ubuntu-latest ]
         python-version: ["3.9", "3.10"]
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v2
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
-      - name: Determine pip cache directory
-        id: pip-cache
-        run: |
-          echo "::set-output name=dir::$(pip cache dir)"
-      - name: Cache pip cache
-        uses: actions/cache@v4
-        with:
-          path: ${{ steps.pip-cache.outputs.dir }}
-          key: ${{ runner.os }}-pip${{ matrix.python-version }}
-      - name: Upgrade pip and install nox
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install nox
-      - name: Run tests
-        run: |
-          nox --non-interactive --session tests-${{ matrix.python-version }}
+      - name: Install dependencies
+        run: pip install tox
 
-  build-docs:
-    name: Test building docs
+      - name: Check manifest
+        run: tox -e manifest
+
+      - name: Check code quality with flake8
+        run: tox -e flake8
+
+      - name: Check package metadata with Pyroma
+        run: tox -e pyroma
+      # - name: Check static typing with MyPy
+      #  run: tox -e mypy
+      #  # Allow failure, see https://github.community/t/continue-on-error-allow-failure-ui-indication/16773
+      #  if: succeeded() || failed()
+  docs:
+    if: "!contains(github.event.head_commit.message, 'skip ci')"
+    name: Documentation
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.9", "3.10"]
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Set up Python ${{ env.default-python }}
+      - uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
-          python-version: ${{ env.default-python }}
-      - name: Upgrade pip and install nox
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: pip install tox
+
+      - name: Check RST conformity with doc8
+        run: tox -e doc8
+
+      - name: Check README.rst
+        run: tox -e readme
+
+      - name: Check documentation build with Sphinx
         run: |
-          python -m pip install --upgrade pip
-          python -m pip install nox
-      - name: Build docs
-        run: |
-          nox --error-on-missing-interpreters --non-interactive --session docs
+          sudo apt-get install graphviz
+          tox -e docs
+  tests:
+    if: "!contains(github.event.head_commit.message, 'skip ci')"
+    name: Tests
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.9", "3.10"]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: pip install tox
+      - name: Run fast tests
+        run: tox -e py
+      - name: Run slow tests
+        run: tox -e integration
