armmbed/mbed-tools/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,76 +1,154 @@
-name: Tests
+name: Integration tests
 
 on:
-  push:
   pull_request:
-  schedule:
-    - cron:  '0 0 * * 0'
+  push:
 
 jobs:
-  standard-tests:
+  mbed-examples:
+    container:
+      image: ghcr.io/armmbed/mbed-os-env:main-latest
+
     runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        target: [K64F, DISCO_L475VG_IOT01A, NRF52840_DK]
+        example:
+          - mbed-os-example-blinky
+          - mbed-os-example-blinky-baremetal
+        profile: [release, debug, develop]
+        include:
+          - example: mbed-os-example-kvstore
+            target: K64F
+            profile: develop
+
+          - example: mbed-os-example-ble
+            subexample: BLE_Advertising
+            target: NRF52840_DK
+            profile: develop
+
+          - example: mbed-os-example-cellular
+            target: WIO_3G
+            profile: develop
+
+          - example: mbed-os-example-devicekey
+            target: K66F
+            profile: develop
+
+          - example: mbed-os-example-lorawan
+            target: DISCO_L072CZ_LRWAN1
+            profile: develop
+
+          - example: mbed-os-example-mbed-crypto
+            subexample: getting-started
+            target: K64F
+            profile: develop
+
+          - example: mbed-os-example-nfc
+            subexample: NFC_EEPROM
+            target: DISCO_L475VG_IOT01A
+            profile: develop
+
+          - example: mbed-os-example-sockets
+            target: K64F
+            profile: develop
+
     steps:
-      - uses: actions/checkout@v2
-      - name: Build the project
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          path: mbedtools
+
+      - name: Install tools
+        run: pip install ./mbedtools
+
+      - name: Build
         run: |
-          echo "UID=$(id --user)" > .env
-          docker-compose up -d --build
-      - name: Lint the code
-        run: |
-          docker-compose exec -T caluma black --check .
-          docker-compose exec -T caluma flake8
-          docker-compose exec -T caluma ./manage.py makemigrations --check --dry-run --no-input
-          docker-compose exec -T caluma reuse lint
-      - name: Run pytest
-        run: docker-compose exec -T caluma pytest --no-cov-on-fail --cov --create-db -vv
-  pipenv-tests:
+          set -e
+          # We use manual clone with depth=1 and single branch for speed
+          git clone --depth=1 --single-branch --branch development https://github.com/ARMmbed/${{ matrix.example }}.git
+          if [ -z ${{ matrix.subexample }} ]; then
+              cd ${{ matrix.example }}
+          else
+              cd ${{ matrix.example }}/${{ matrix.subexample }}
+          fi
+
+          mbed-tools deploy
+          mbed-tools -vvv compile -t GCC_ARM -m ${{ matrix.target }} --profile ${{ matrix.profile }}
+
+  test-project-management:
+    container:
+      image: ghcr.io/armmbed/mbed-os-env:main-latest
+
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v2
-      - name: Setup Python
-        uses: actions/setup-python@v1
+      - name: Checkout
+        uses: actions/checkout@v2
         with:
-          python-version: '3.9'
-      - name: Install requirements
-        env:
-          PIPENV_IGNORE_VIRTUALENVS: 1
+          path: mbedtools
+
+      - name: Install tools
+        run: pip install ./mbedtools
+
+      - name: New project with new directory
         run: |
-          pip install pipenv
-          python3 setup.py pipenv
-      - name: Run pytest
-        run: pipenv run pytest
-  package-tests:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Setup Python
-        uses: actions/setup-python@v1
-        with:
-          python-version: '3.9'
-      - name: Install package
+          mbedtools new test
+          cd test
+          mbedtools compile -t GCC_ARM -m K64F
+
+      - name: New project in pwd
         run: |
-          echo UID=$(id -u) > .env
-          echo ENV=dev >> .env
-          docker-compose up -d db
-          rm -rf dist/
-          python -m pip install --upgrade pip
-          pip install setuptools wheel
-          python setup.py bdist_wheel
-          pip install dist/caluma-*.whl
-          pip install -r requirements-dev.txt
-      - name: Run pytest
-        run: pytest --no-cov-on-fail --cov --create-db -vv
-  gitlint:
+          mkdir mbed-os-example && cd mbed-os-example
+          mbedtools new .
+          mbedtools compile -t GCC_ARM -m K64F
+
+      - name: Import
+        run: |
+          mbedtools import mbed-os-example-ble
+          cd mbed-os-example-ble
+          # Checkout the development branch on BLE example
+          git fetch origin development
+          git checkout FETCH_HEAD
+          cd BLE_Advertising
+          mbedtools deploy
+          mbedtools compile -t GCC_ARM -m K64F
+
+      - name: Deploy
+        run: |
+          mkdir deploy-test
+          cd deploy-test
+          echo "https://github.com/ARMmbed/mbed-os" > mbed-os.lib
+          git clone --branch=latest https://github.com/ARMmbed/mbed-os.git
+          mbedtools -vvv deploy
+          cd mbed-os
+          git branch --points-at origin/HEAD
+          git branch --points-at origin/HEAD | grep -q "\*" || (echo "Couldn't
+          see current branch points at default branch" && false)
+
+  test-custom-target:
+    container:
+      image: ghcr.io/armmbed/mbed-os-env:main-latest
+
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout
+        uses: actions/checkout@v2
         with:
-          fetch-depth: 0
-      - name: Setup Python
-        uses: actions/setup-python@v1
-        with:
-          python-version: '3.9'
-      - name: Install gitlint
-        run: pip install gitlint
-      - name: Run gitlint
-        run: gitlint --contrib contrib-title-conventional-commits
+          path: mbedtools
+
+      - name: Install tools
+        run: pip install ./mbedtools
+
+      - name: Build
+        run: |
+          mbedtools new custom-target-test
+          cd custom-target-test
+          cp ../mbedtools/ci/test-data/custom_targets.json .
+          mkdir TARGET_IMAGINARYBOARD
+          cp ../mbedtools/ci/test-data/TARGET_IMAGINARYBOARD/* TARGET_IMAGINARYBOARD
+          cp mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/P* TARGET_IMAGINARYBOARD
+          sed -i '/add_subdirectory(${MBED_PATH})/i add_subdirectory(TARGET_IMAGINARYBOARD)' CMakeLists.txt
+          mbedtools compile -t GCC_ARM -m IMAGINARYBOARD
