mykrobe-tools/mykrobe/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,158 +1,214 @@
-name: Modoboa webmail plugin
+name: Mykrobe builds
 
 on:
   push:
-    branches: [ main ]
+    tags:
+    - 'v*.*.*'
+    branches:
+      - main
   pull_request:
-    branches: [ main ]
-  release:
-    branches: [ main ]
+    branches:
+      - main
 
 env:
-  POSTGRES_HOST: localhost
+  REGISTRY: ghcr.io
+  IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  test:
-    runs-on: ubuntu-latest
-    services:
-      postgres:
-        image: postgres:11
-        env:
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-          POSTGRES_DB: postgres
-        ports:
-        # will assign a random free host port
-        - 5432/tcp
-        # needed because the postgres container does not provide a healthcheck
-        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
-      mysql:
-        image: mysql:8.0
-        env:
-          MYSQL_ROOT_PASSWORD: root
-          MYSQL_USER: modoboa
-          MYSQL_PASSWORD: modoboa
-          MYSQL_DATABASE: modoboa
-        ports:
-          - 3306/tcp
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
-
-    strategy:
-      matrix:
-        database: ['postgres', 'mysql']
-        python-version: ["3.9", "3.10"]
-      fail-fast: false
-
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
-        run: |
-          sudo apt-get update -y && sudo apt-get install -y librrd-dev rrdtool 
-          python -m pip install --upgrade pip
-          pip install -e git+https://github.com/modoboa/modoboa.git#egg=modoboa
-          pip install -r requirements.txt
-          pip install -r test-requirements.txt
-          python setup.py develop
-      - name: Install postgres requirements
-        if: ${{ matrix.database == 'postgres' }}
-        run: |
-          pip install psycopg2-binary>=2.7.4
-          pip install coverage
-          echo "DB=postgres" >> $GITHUB_ENV
-      - name: Install mysql requirements
-        if: ${{ matrix.database == 'mysql' }}
-        run: |
-          pip install 'mysqlclient<2.0.4'
-          echo "DB=mysql" >> $GITHUB_ENV
-      - name: Test with pytest
-        if: ${{ matrix.python-version != '3.8' || matrix.database != 'postgres' }}
-        run: |
-          cd test_project
-          python3 manage.py test modoboa_webmail
-        env:
-          # use localhost for the host here because we are running the job on the VM.
-          # If we were running the job on in a container this would be postgres
-          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
-          MYSQL_HOST: 127.0.0.1
-          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }} # get randomly assigned published port
-          MYSQL_USER: root
-
-      - name: Test with pytest and coverage
-        if: ${{ matrix.python-version == '3.8' && matrix.database == 'postgres' }}
-        run: |
-          cd test_project
-          coverage run --source ../modoboa_webmail manage.py test modoboa_webmail
-        env:
-          # use localhost for the host here because we are running the job on the VM.
-          # If we were running the job on in a container this would be postgres
-          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
-          MYSQL_HOST: 127.0.0.1
-          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }} # get randomly assigned published port
-          MYSQL_USER: root
-      - name: Upload coverage result
-        if: ${{ matrix.python-version == '3.8' }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-results
-          path: test_project/.coverage
-
-  coverage:
-    needs: test
+  build_containers:
+    name: Build linux/singularity container
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'
-      - name: Install dependencies
-        run: |
-          pip install codecov
-      - name: Download coverage results
-        uses: actions/download-artifact@v2
-        with:
-          name: coverage-results
-      - name: Report coverage
-        run: |
-          coverage report
-          codecov
 
-  release:
-    needs: coverage
-    runs-on: ubuntu-latest
+    - name: Set up Go 1.16
+      uses: actions/setup-go@v1
+      with:
+        go-version: 1.16
+      id: go
+
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update && sudo apt-get install -y \
+          build-essential \
+          libssl-dev \
+          uuid-dev \
+          libgpgme11-dev \
+          squashfs-tools \
+          libseccomp-dev \
+          pkg-config \
+          debootstrap \
+          debian-keyring \
+          debian-archive-keyring \
+          rsync
+
+    - name: Install Singularity
+      env:
+        SINGULARITY_VERSION: 3.5.3
+        GOPATH: /tmp/go
+      run: |
+        mkdir -p $GOPATH
+        sudo mkdir -p /usr/local/var/singularity/mnt
+        mkdir -p $GOPATH/src/github.com/sylabs
+        cd $GOPATH/src/github.com/sylabs
+        wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
+        tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
+        cd singularity
+        ./mconfig -v -p /usr/local
+        make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
+        sudo make -C ./builddir install
+
+
+    - name: Check out code for the container build
+      uses: actions/checkout@v2
+
+    - name: Set release version if is a release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+
+    - name: Set release version if not a release
+      if: false == startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
+
+    - name: Build Singularity container
+      env:
+        SINGULARITY_RECIPE: Singularity.def
+        OUTPUT_CONTAINER: mykrobe_${{env.RELEASE_VERSION}}.img
+      run: |
+        ls
+        if [ -f "${SINGULARITY_RECIPE}" ]; then
+            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
+        else
+            echo "${SINGULARITY_RECIPE} is not found."
+            echo "Present working directory: $PWD"
+            ls
+        fi
+
+    - name: Release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      uses: softprops/action-gh-release@v1
+      with:
+        files: mykrobe*.img
+        draft: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  mac_build:
+    name: Build mac os command line
+    runs-on: macos-11
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - name: Set up Python 3.8
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'
-      - name: Build packages
-        run: |
-          sudo apt-get install librrd-dev rrdtool libssl-dev gettext
-          python -m pip install --upgrade pip setuptools wheel
-          pip install -r requirements.txt
-          cd modoboa_webmail
-          django-admin compilemessages
-          cd ..
-          python setup.py sdist bdist_wheel
-      - name: Publish to Test PyPI
-        if: endsWith(github.event.ref, '/main')
-        uses: pypa/gh-action-pypi-publish@main
-        with:
-          user: __token__
-          password: ${{ secrets.test_pypi_password }}
-          repository_url: https://test.pypi.org/legacy/
-          skip_existing: true
-      - name: Publish distribution to PyPI
-        if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
-        uses: pypa/gh-action-pypi-publish@main
-        with:
-          user: __token__
-          password: ${{ secrets.pypi_password }}
-          skip_existing: true
+
+    - name: Install dependencies
+      run: |
+        pip3 install cython requests wheel tox pyinstaller
+
+    - name: Check out code for the build
+      uses: actions/checkout@v2
+
+    - name: Set release version if is a release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+
+    - name: Set release version if not a release
+      if: false == startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
+
+    - name: Test and build command line tarball
+      env:
+        OUTPUT_TARBALL: mykrobe.command_line.osx.${{env.RELEASE_VERSION}}.tar.gz
+      run: |
+        # mongod default data directory is /data/db, which is not writeable.
+        mkdir $HOME/mongodb_data
+        chown -R `id -un` $HOME/mongodb_data
+        sudo mongod --dbpath=$HOME/mongodb_data --quiet &> /dev/null &
+        sleep 3s
+        rm -rf .tox
+        sudo tox
+        sudo pip3 install .
+        mykrobe panels update_metadata --panels_dir src/mykrobe/data
+        mykrobe panels update_species --panels_dir src/mykrobe/data --debug all
+        cd dist
+        pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
+        cd pyinstaller_build
+        tar cvfz ../../${OUTPUT_TARBALL} mykrobe_atlas/
+
+    - name: Release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      uses: softprops/action-gh-release@v1
+      with:
+        files: mykrobe.command_line.osx.*.tar.gz
+        draft: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  windows_build:
+    name: Build Windows command line
+    runs-on: windows-2019
+    steps:
+    - uses: msys2/setup-msys2@v2
+      with:
+        update: true
+        install: >-
+          autotools gcc git libcurl-devel bzip2 liblzma zip libbz2-devel xz zlib zlib-devel libtool wget liblzma-devel ncurses-devel base-devel openssl-devel mingw64/mingw-w64-x86_64-python3 mingw64/mingw-w64-x86_64-python3-pip mingw-w64-x86_64-python3-numpy mingw-w64-x86_64-python3-setuptools mingw-w64-x86_64-python3-wheel mingw-w64-x86_64-python-biopython
+
+    - name: Check out code for the build
+      uses: actions/checkout@v2
+
+    - name: Set release version if is a release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+      shell: msys2 {0}
+
+    - name: Set release version if not a release
+      if: false == startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
+      shell: msys2 {0}
+
+    - name: Test and build command line tarball
+      env:
+        OUTPUT_TARBALL: mykrobe.command_line.windows.${{env.RELEASE_VERSION}}.tar.gz
+      run: |
+        export PYTHONPATH="/mingw64/lib/python3.9/:/mingw64/lib/python3.9/site-packages:${PYTHONPATH}"
+        C:\\msys64\\mingw64\\bin\\python3.exe -m pip install pyinstaller requests pytest
+
+        echo "clone mccortex"
+        rm -rf mccortex
+        git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex
+        cd mccortex/libs/htslib
+        git checkout bcf9bff178f81c9c1cf3a052aeb6cbe32fe5fdcc
+        cd ../bcftools
+        git checkout b406a3906b153faa8bec0a53df07b2adf18a3052
+        cd ../samtools
+        git checkout 2d4907cf9a34ccf7cde60143158b39e1cb40ac0c
+        cd ../../../
+        python ./ci/windows_file_fixes.py
+        cd mccortex
+        echo "make mccortex"
+        make all
+        echo "make tests mccortex"
+        make tests
+        cd ..
+
+        echo "pip install requirements"
+        C:\\msys64\\mingw64\\bin\\python3.exe -m pip install -r requirements.txt
+        echo "pip install ."
+        C:\\msys64\\mingw64\\bin\\python3.exe -m pip install .
+        echo "pytest"
+        export MYKROBE_MCCORTEX="${PWD}/mccortex/bin/mccortex31"
+        C:\\msys64\\mingw64\\bin\\python3.exe -m pytest
+        echo "update panels"
+        C:\\msys64/mingw64/bin/mykrobe.exe panels update_metadata --panels_dir src/mykrobe/data
+        C:\\msys64/mingw64/bin/mykrobe.exe panels update_species --panels_dir src/mykrobe/data --debug all
+        cd dist
+        C:\\msys64/mingw64/bin/pyinstaller.exe --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller_windows.spec
+        cd pyinstaller_build
+        tar cvfz ../../${OUTPUT_TARBALL} mykrobe_atlas/
+      shell: msys2 {0}
+
+    - name: Release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      uses: softprops/action-gh-release@v1
+      with:
+        files: mykrobe.command_line.windows.*.tar.gz
+        draft: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
