horazont/aioxmpp/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,43 +1,160 @@
+name: CI
+
 on:
   push:
     branches:
-      - main
+    - devel
+    - main
+    - "release-*"
   pull_request:
     branches:
-      - main
+    - devel
+    - main
+    - "release-*"
+  workflow_dispatch:
 
 jobs:
   test:
     runs-on: ubuntu-latest
+
     strategy:
-     matrix:
-      include:
-        - { vim_version: "7.4", python_image: "3.5-stretch", tag: "vim_74_py35" }
-        - { vim_version: "8.0", python_image: "3.5-stretch", tag: "vim_80_py35" }
-        - { vim_version: "8.1", python_image: "3.5-stretch", tag: "vim_81_py35" }
-        - { vim_version: "git", python_image: "3.5-stretch", tag: "vim_git_py35" }
+      matrix:
+        python-version: ["3.9", "3.10"]
+        test-type:
+        - e2e
+        e2e-software:
+        - prosody
+        e2e-version:
+        - '0.11'
 
-        - { vim_version: "7.4", python_image: "3.6-stretch", tag: "vim_74_py36" }
-        - { vim_version: "8.0", python_image: "3.6-stretch", tag: "vim_80_py36" }
-        - { vim_version: "8.1", python_image: "3.6-stretch", tag: "vim_81_py36" }
-        - { vim_version: "git", python_image: "3.6-stretch", tag: "vim_git_py36" }
+        include:
+        # e2e-tests for non-default prosody will be run with the Python
+        # version available in debian stable
+        - python-version: '3.9'
+          test-type: e2e
+          e2e-software: prosody
+          e2e-version: '0.9'
+        - python-version: '3.9'
+          test-type: e2e
+          e2e-software: prosody
+          e2e-version: '0.10'
+        - python-version: '3.9'
+          test-type: e2e
+          e2e-software: ejabberd
+          e2e-version: '18.09'
+        - python-version: '3.9'
+          test-type: e2e
+          e2e-software: ejabberd
+          e2e-version: '19.08'
+        # plain unit test runs with most recent python version
+        - python-version: '3.9'
+          test-type: unit
+          e2e-software: coveralls
+          e2e-version: latest
+        # no proper allow-failure in GitHub actions, so we have to disable
+        # those instead :(
+        # (see https://github.com/actions/toolkit/issues/399)
+        # - python-version: '3.9'
+        #   test-type: e2e
+        #   e2e-software: prosody
+        #   e2e-version: 'trunk'
+        # - python-version: '3.9'
+        #   test-type: e2e
+        #   e2e-software: metronome
+        #   e2e-version: 'main'
+        # - python-version: '3.9'
+        #   test-type: e2e
+        #   e2e-software: ejabberd
+        #   e2e-version: latest
 
-        - { vim_version: "8.1", python_image: "3.7-stretch", tag: "vim_81_py37" }
-        - { vim_version: "8.2", python_image: "3.7-stretch", tag: "vim_82_py37" }
-        - { vim_version: "git", python_image: "3.7-stretch", tag: "vim_git_py37" }
+    name: '${{ matrix.test-type }}: py${{ matrix.python-version }}, ${{ matrix.e2e-software }}@${{ matrix.e2e-version }}'
 
-        - { vim_version: "8.1", python_image: "3.8-buster", tag: "vim_81_py38" }
-        - { vim_version: "8.2", python_image: "3.8-buster", tag: "vim_82_py38" }
-        - { vim_version: "git", python_image: "3.8-buster", tag: "vim_git_py38" }
-
-        - { vim_version: "8.1", python_image: "3.9-buster", tag: "vim_81_py39" }
-        - { vim_version: "8.2", python_image: "3.9-buster", tag: "vim_82_py39" }
-        - { vim_version: "git", python_image: "3.8-buster", tag: "vim_git_py39" }
-
-    name: Build & Test using Docker
     steps:
       - uses: actions/checkout@v2
-      - name: Build the image
-        run: docker build -t ultisnips:${{ matrix.tag }} --build-arg PYTHON_IMAGE=${{ matrix.python_image }} --build-arg VIM_VERSION=${{ matrix.vim_version }} .
-      - name: Run the tests
-        run: docker run --rm -t ultisnips:${{ matrix.tag }} docker/run_tests.sh
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '${{ matrix.python-version }}'
+      - name: Install Prosody
+        if: matrix.e2e-software == 'prosody'
+        run: |
+          set -euo pipefail
+          export PATH=$PWD/lua_install/bin:$PATH
+          # enable source repositories for build dependencies
+          sudo sed -ri 's/^# deb-src/deb-src/' /etc/apt/sources.list /etc/apt/sources.list.d/*
+          sudo apt-get update
+          ./utils/install-prosody.sh
+        env:
+          WITH_BUILD_DEP: "yes"
+          PROSODY_BRANCH: "${{ matrix.e2e-version }}"
+          LUA_VERSION: "5.1"
+      - name: Install Metronome
+        if: matrix.e2e-software == 'metronome'
+        run: |
+          set -euo pipefail
+          export PATH=$PWD/lua_install/bin:$PATH
+          # enable source repositories for build dependencies
+          sudo sed -ri 's/^# deb-src/deb-src/' /etc/apt/sources.list /etc/apt/sources.list.d/*
+          sudo apt-get update
+          sudo apt-get install libevent-dev
+          ./utils/install-metronome.sh
+        env:
+          WITH_BUILD_DEP: "yes"
+          METRONOME_VERSION: "${{ matrix.e2e-version }}"
+      - name: Prepare ejabberd
+        if: matrix.e2e-software == 'ejabberd'
+        run: |
+          set -euo pipefail
+          ./utils/prepare-ejabberd.sh
+        env:
+          EJABBERD_VERSION: "${{ matrix.e2e-version }}"
+      - name: Install aioxmpp and test utils
+        run: |
+          set -euo pipefail
+          pip install nose coveralls pyOpenSSL
+          pip install .
+      - name: Run test suite
+        run: |
+          set -euo pipefail
+          export PATH=$PWD/lua_install/bin:$PATH
+          if [[ "x$TEST_TYPE" = 'xunit' ]]; then
+            nosetests --with-cover --cover-package aioxmpp tests
+          else
+            case "$E2E_SOFTWARE" in
+              prosody)
+                export PROSODY_BRANCH="$E2E_VERSION"
+                ./utils/travis-e2etest-prosody.py
+                ;;
+              metronome)
+                export METRONOME_VERSION="$E2E_VERSION"
+                ./utils/travis-e2etest-metronome.py
+                ;;
+              ejabberd)
+                export EJABBERD_VERSION="$E2E_VERSION"
+                ./utils/travis-e2etest-ejabberd.py
+                ;;
+              *)
+                echo "Invalid e2e software: ${E2E_SOFTWARE}" >&2
+                exit 1
+                ;;
+            esac
+          fi
+        env:
+          TEST_TYPE: ${{ matrix.test-type }}
+          E2E_SOFTWARE: ${{ matrix.e2e-software }}
+          E2E_VERSION: ${{ matrix.e2e-version }}
+      - name: Coveralls
+        uses: AndreMiras/coveralls-python-action@develop
+        if: matrix.test-type == 'unit'
+        with:
+          parallel: true
+          flag-name: unit
+
+  finish:
+    needs: test
+    runs-on: ubuntu-latest
+    name: Finalize
+    steps:
+    - name: Finalize Coveralls interaction
+      uses: AndreMiras/coveralls-python-action@develop
+      with:
+        parallel-finished: true
